"use client";

import type { InukaRiskCase } from "@/lib/types";

function formatKes(value: number): string { return new Intl.NumberFormat("en-KE", { style: "currency", currency: "KES", maximumFractionDigits: 0 }).format(value); }

export default function InukaCaseModal({ item, onClose }: { item: InukaRiskCase; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-label="Assurance case details" onClick={onClose}><div className="w-full max-w-xl rounded-xl border border-border bg-card p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Case details</p><h2 className="mt-1 text-xl font-bold text-foreground">{item.title}</h2><p className="mt-1 font-mono text-[10px] text-muted-foreground">{item.case_id}</p></div><button onClick={onClose} className="rounded-md px-2 py-1 text-xl text-muted-foreground hover:bg-muted" aria-label="Close">×</button></div><div className="mt-5 rounded-lg bg-muted/40 p-4"><p className="text-sm font-medium text-foreground">Why it was flagged</p><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{item.reason}</p></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-[10px] uppercase text-muted-foreground">Pillar</p><p className="mt-1 font-semibold text-foreground">{item.pillar_id || "Unassigned"}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Beneficiary</p><p className="mt-1 font-semibold text-foreground">{item.beneficiary_id || "Unassigned"}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Officer</p><p className="mt-1 font-semibold text-foreground">{item.officer_id || "Unassigned"}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Period</p><p className="mt-1 font-semibold text-foreground">{item.period || "Unassigned"}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Amount at risk</p><p className="mt-1 font-mono font-semibold text-status-critical">{formatKes(item.amount_at_risk)}</p></div><div><p className="text-[10px] uppercase text-muted-foreground">Risk confidence</p><p className="mt-1 font-semibold capitalize text-foreground">{item.confidence}</p></div></div><div className="mt-5 border-t border-border pt-4"><p className="text-[10px] uppercase text-muted-foreground">Source records</p><div className="mt-2 flex flex-wrap gap-2">{item.source_records.length ? item.source_records.map((record) => <span key={record} className="rounded-full bg-muted px-2 py-1 font-mono text-[11px] text-muted-foreground">{record}</span>) : <span className="text-sm text-muted-foreground">No source record attached.</span>}</div></div><div className="mt-6 flex justify-end"><button onClick={onClose} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Close case details</button></div></div></div>;
}
