import{createContext,useContext,useMemo,useState}from"react";
import{Modal,ScrollView,Pressable,StyleSheet,Text,View}from"react-native";
import{Ionicons}from"@expo/vector-icons";import{router,usePathname,useLocalSearchParams}from"expo-router";import{useSafeAreaInsets}from"react-native-safe-area-context";
import{useAuth}from"./auth";import{c}from"./theme";
export type Workspace="oil"|"inuka";type ShellValue={workspace:Workspace;setWorkspace:(v:Workspace)=>void;openMenu:()=>void};const C=createContext<ShellValue|null>(null);
type MenuItem={label:string;icon:keyof typeof Ionicons.glyphMap;permission?:string;route:string;badge?:boolean};
const oil:MenuItem[]=[{label:"Depot gate preview",icon:"car-outline",permission:"view_metrics",route:"/(tabs)/gate"},{label:"Manifest scanner",icon:"scan-outline",permission:"upload_csv",route:"/(tabs)/scanner"},{label:"Dashboard",icon:"grid-outline",route:"/(tabs)"},{label:"Anomalies",icon:"warning-outline",permission:"view_anomaly_table",route:"/(tabs)/anomalies",badge:true},{label:"Leakage Explorer",icon:"bar-chart-outline",permission:"view_heatmap",route:"/(tabs)/feature?name=Leakage%20Explorer&icon=bar-chart-outline"},{label:"Risk Intelligence",icon:"git-network-outline",permission:"view_fraud_graph",route:"/(tabs)/risk"},{label:"E-Billing",icon:"card-outline",permission:"manage_ebilling",route:"/(tabs)/feature?name=E-Billing&icon=card-outline"},{label:"Reports",icon:"documents-outline",permission:"export_reports",route:"/(tabs)/feature?name=Reports&icon=documents-outline"},{label:"Audit Trail",icon:"clipboard-outline",permission:"view_audit",route:"/(tabs)/feature?name=Audit%20Trail&icon=clipboard-outline"}];
const inuka:MenuItem[]=[{label:"Assurance Overview",icon:"grid-outline",route:"/(tabs)"},{label:"Anomalies",icon:"warning-outline",permission:"view_anomaly_table",route:"/(tabs)/anomalies",badge:true},{label:"Leakage Explorer",icon:"bar-chart-outline",permission:"view_heatmap",route:"/(tabs)/feature?name=Leakage%20Explorer&icon=bar-chart-outline"},{label:"Risk Intelligence",icon:"git-network-outline",permission:"view_fraud_graph",route:"/(tabs)/risk"},{label:"Beneficiary Verification",icon:"location-outline",permission:"resolve_anomaly",route:"/(tabs)/field"},{label:"Beneficiaries",icon:"people-outline",permission:"view_anomaly_table",route:"/(tabs)/feature?name=Beneficiaries&icon=people-outline"},{label:"Reports",icon:"documents-outline",permission:"export_reports",route:"/(tabs)/feature?name=Reports&icon=documents-outline"},{label:"Audit Trail",icon:"clipboard-outline",permission:"view_audit",route:"/(tabs)/feature?name=Audit%20Trail&icon=clipboard-outline"}];
export function ShellProvider({children}:{children:React.ReactNode}){const{user,logout}=useAuth(),[open,setOpen]=useState(false);const inukaOnly=user?.roles.includes("inuka_manager")??false;const[selectedWorkspace,setWorkspaceState]=useState<Workspace>(inukaOnly?"inuka":"oil");const canDual=!inukaOnly&&!user?.roles.includes("depot_supervisor")&&(user?.permissions.includes("view_outgoing_data")??false);const workspace:Workspace=inukaOnly?"inuka":canDual?selectedWorkspace:"oil";const visible=(workspace==="inuka"?inuka:oil).filter(x=>!x.permission||user?.permissions.includes(x.permission));const value=useMemo(()=>({workspace,setWorkspace:(v:Workspace)=>{if(canDual){setWorkspaceState(v);router.replace("/(tabs)")}},openMenu:()=>setOpen(true)}),[workspace,canDual]);async function out(){setOpen(false);await logout();router.replace("/login")}return <C.Provider value={value}><MobileAccess>{children}</MobileAccess><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><Pressable style={s.scrim} onPress={()=>setOpen(false)}/><View style={s.drawer}><View style={s.brandRow}><Pressable onPress={()=>setOpen(false)} hitSlop={12}><Ionicons name="close" size={22} color={c.sidebarMuted}/></Pressable><Brand compact/></View><Text style={s.kicker}>WORKSPACE</Text>{canDual&&<View style={s.switcher}>{(["oil","inuka"]as Workspace[]).map(w=><Pressable key={w} style={[s.switch,workspace===w&&s.switchOn]} onPress={()=>{setWorkspaceState(w);setOpen(false);router.replace("/(tabs)")}}><Text style={[s.switchText,workspace===w&&s.switchTextOn]}>{w==="oil"?"Oil Revenue":"Inuka Programs"}</Text></Pressable>)}</View>}<ScrollView style={{flex:1}} contentContainerStyle={s.nav}>{visible.map(item=><Pressable key={item.label} style={s.navItem} onPress={()=>{setOpen(false);router.push(item.route as never)}}><Ionicons name={item.icon} size={20} color={c.sidebarMuted}/><Text style={s.navText}>{item.label}</Text></Pressable>)}</ScrollView><View style={s.account}><View style={s.avatar}><Text style={s.avatarText}>{user?.email?.[0]?.toUpperCase()??"K"}</Text></View><View style={{flex:1}}><Text numberOfLines={1} style={s.email}>{user?.email}</Text><Text numberOfLines={1} style={s.role}>{user?.roles.join(", ").replace(/_/g," ")}</Text></View><Pressable onPress={out}><Ionicons name="log-out-outline" size={20} color={c.sidebarMuted}/></Pressable></View></View></View></Modal></C.Provider>}
export function useShell(){const v=useContext(C);if(!v)throw new Error("ShellProvider missing");return v}
export function Brand({compact=false}:{compact?:boolean}){return <View style={s.brand}><View style={[s.mark,compact&&{width:27,height:27}]}><View style={s.drop}/><Text style={s.kpc}>KPC</Text></View><View style={{flexShrink:1}}><Text numberOfLines={1} style={s.brandName}>Kenya Pipeline Company</Text><Text numberOfLines={1} style={s.brandSub}>Reconova Enterprise Intelligence System</Text></View></View>}
export function MobileHeader(){const{openMenu,workspace}=useShell();const insets=useSafeAreaInsets();return <View style={[s.header,{paddingTop:Math.max(insets.top,10)}]}><Pressable onPress={openMenu} style={s.iconButton}><Ionicons name="menu" size={24} color={c.muted}/></Pressable><View style={s.search}><Ionicons name="search" size={16} color={c.muted}/><Text style={s.searchText}>{workspace==="inuka"?"Inuka program assurance":"Oil revenue assurance"}</Text></View><Pressable onPress={()=>router.push("/(tabs)/alerts")} style={s.bell}><Ionicons name="notifications-outline" size={21} color={c.text}/></Pressable></View>}
const s=StyleSheet.create({overlay:{flex:1,flexDirection:"row"},scrim:{...StyleSheet.absoluteFill,backgroundColor:"rgba(0,0,0,.43)"},drawer:{width:"78%",maxWidth:340,backgroundColor:c.sidebar,padding:18,paddingTop:34},brandRow:{flexDirection:"row",alignItems:"center",gap:18,marginBottom:28},brand:{flexDirection:"row",alignItems:"center",gap:10,flex:1},mark:{width:34,height:34,borderRadius:10,backgroundColor:"#FFF",alignItems:"center",justifyContent:"center",overflow:"hidden"},drop:{position:"absolute",top:5,width:0,height:0,borderLeftWidth:7,borderRightWidth:7,borderBottomWidth:14,borderLeftColor:"transparent",borderRightColor:"transparent",borderBottomColor:c.red},kpc:{fontSize:7,fontWeight:"900",color:"#FFF",backgroundColor:"#111",padding:2,borderRadius:5,marginTop:10},brandName:{color:c.sidebarText,fontWeight:"800",fontSize:13},brandSub:{color:c.sidebarMuted,fontSize:9,marginTop:3},kicker:{fontSize:9,fontWeight:"800",letterSpacing:1.2,color:c.sidebarMuted,marginBottom:10},switcher:{flexDirection:"row",padding:4,backgroundColor:c.sidebarCard,borderRadius:9,marginBottom:15},switch:{flex:1,paddingVertical:10,alignItems:"center",borderRadius:7},switchOn:{backgroundColor:c.green},switchText:{fontSize:10,fontWeight:"700",color:c.sidebarMuted},switchTextOn:{color:"white"},nav:{gap:2},navItem:{minHeight:42,borderRadius:7,flexDirection:"row",alignItems:"center",gap:13,paddingHorizontal:10},navText:{color:c.sidebarMuted,fontSize:14,flex:1},badge:{width:20,height:20,borderRadius:10,backgroundColor:c.red,alignItems:"center",justifyContent:"center"},badgeText:{color:"white",fontSize:10,fontWeight:"900"},account:{marginTop:"auto",borderTopWidth:1,borderTopColor:"#332B28",paddingTop:14,flexDirection:"row",alignItems:"center",gap:10},avatar:{width:30,height:30,borderRadius:15,backgroundColor:"#482421",alignItems:"center",justifyContent:"center"},avatarText:{color:c.red,fontWeight:"800"},email:{color:c.sidebarText,fontWeight:"700",fontSize:11},role:{color:c.sidebarMuted,fontSize:9,textTransform:"capitalize",marginTop:2},header:{minHeight:62,paddingBottom:9,paddingHorizontal:14,backgroundColor:c.card,borderBottomWidth:1,borderBottomColor:c.line,flexDirection:"row",alignItems:"center",gap:10},iconButton:{padding:5},search:{height:38,flex:1,flexDirection:"row",alignItems:"center",gap:8,backgroundColor:c.bg,borderWidth:1,borderColor:c.line,borderRadius:7,paddingHorizontal:11},searchText:{flex:1,fontSize:12,color:c.text},bell:{padding:5},dot:{position:"absolute",right:3,top:3,width:7,height:7,borderRadius:4,backgroundColor:c.red,borderWidth:1,borderColor:"white"}})

function MobileAccess({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth();
  const { workspace } = useShell();
  const path = usePathname();
  const params = useLocalSearchParams<{ name?: string }>();
  const route = path.split("/").pop() || "index";
  const permissions: Record<string, string> = { index: "view_metrics", anomalies: "view_anomaly_table", risk: "view_fraud_graph", field: "resolve_anomaly", scanner: "upload_csv", gate: "view_metrics", assistant: "view_anomaly_table" };
  const features: Record<string, string> = { "E-Billing": "manage_ebilling", "Reports": "export_reports", "Audit Trail": "view_audit", "Beneficiaries": "view_anomaly_table", "Leakage Explorer": "view_heatmap" };
  const required = route === "feature" ? features[params.name ?? ""] : permissions[route];
  const wrongWorkspace = (workspace === "inuka" && ["gate", "scanner"].includes(route)) || (workspace === "oil" && route === "field") || (route === "feature" && ((workspace === "inuka" && params.name === "E-Billing") || (workspace === "oil" && params.name === "Beneficiaries")));
  if (loading) return <View style={{ padding: 24 }}><Text>Loading account…</Text></View>;
  if (!user || (user.roles.includes("system_admin") && route !== "profile") || wrongWorkspace || (required && !user.permissions.includes(required)) || (route === "feature" && !required)) return <View style={{ flex: 1, backgroundColor: c.bg, padding: 24, justifyContent: "center" }}><Text style={{ fontSize: 22, fontWeight: "700", color: c.text }}>Module unavailable</Text><Text style={{ marginTop: 12, color: c.muted }}>Your workspace or role does not allow this module. Administrators manage access from the web console.</Text><Pressable onPress={() => router.replace("/(tabs)/profile")}><Text style={{ marginTop: 20, color: c.blue }}>Open profile</Text></Pressable></View>;
  return <>{children}</>;
}
