"""create anomaly_resolutions table

Revision ID: 7006ae60f40a
Revises: ad9d3a7fd58f
Create Date: 2026-07-23 13:29:11.137968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7006ae60f40a'
down_revision: Union[str, Sequence[str], None] = 'ad9d3a7fd58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_resolutions',
    sa.Column('dispatch_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('dispatch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_resolutions')
    # ### end Alembic commands ###
