"""create quota_ledger table

Revision ID: e3e5732b72b4
Revises: 7006ae60f40a
Create Date: 2026-07-23 15:35:28.014753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e5732b72b4'
down_revision: Union[str, Sequence[str], None] = '7006ae60f40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_ledger',
    sa.Column('omc_id', sa.Text(), nullable=False),
    sa.Column('base_quota_litres', sa.Integer(), nullable=True),
    sa.Column('current_quota_litres', sa.Integer(), nullable=True),
    sa.Column('trailing_window_days', sa.Integer(), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('omc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quota_ledger')
    # ### end Alembic commands ###
